name: Varbase Media Base
description: A base recipe to install core media modules and apply default Varbase media configurations including media library, focal point, and media types.
type: Varbase Media
recipes:
  - core/recipes/audio_media_type
  - core/recipes/image_media_type
  - core/recipes/local_video_media_type
  - core/recipes/remote_video_media_type
install:
  - media
  - media_library
  - file
  - image
  - breakpoint
  - views
  - better_exposed_filters
  - crop
  - drimage_improved
  - dropzonejs_eb_widget
  - embed
  - focal_point
  - field_ui
  - media_bulk_upload
  - media_bulk_upload_dropzonejs
  - media_library_edit
  - views_bulk_operations
  - views_infinite_scroll
  - views_bulk_edit
  - varbase_media
config:
  actions:
    core.entity_form_display.media.video.default:
      setComponent:
        name: field_media_cover_image
        options:
          type: image_focal_point
          weight: 20
          region: content
          settings:
            progress_indicator: throbber
            preview_image_style: field_preview
            preview_link: true
            offsets: '50,50'
          third_party_settings: {}
    core.entity_view_display.media.video.default:
      setComponent:
        name: field_media_cover_image
        options:
          type: image
          label: hidden
          weight: 1
          region: content
          settings:
            image_style: ''
            image_link: ''
            image_loading:
              attribute: lazy
          third_party_settings: {}
    core.entity_form_display.media.remote_video.default:
      setComponent:
        name: field_media_cover_image
        options:
          type: image_focal_point
          weight: 20
          region: content
          settings:
            progress_indicator: throbber
            preview_image_style: field_preview
            preview_link: true
            offsets: '50,50'
          third_party_settings: {}
    core.entity_view_display.media.remote_video.default:
      setComponent:
        name: field_media_cover_image
        options:
          type: image
          label: hidden
          weight: 1
          region: content
          settings:
            image_style: ''
            image_link: ''
            image_loading:
              attribute: lazy
          third_party_settings: {}
    core.entity_view_display.media.video.media_library:
      setComponent:
        name: field_media_cover_image
        options:
          type: image
          label: hidden
          weight: 1
          region: content
          settings:
            image_style: medium
            image_link: ''
            image_loading:
              attribute: lazy
          third_party_settings: {}
    core.entity_view_display.media.remote_video.media_library:
      setComponent:
        name: field_media_cover_image
        options:
          type: image
          label: hidden
          weight: 1
          region: content
          settings:
            image_style: medium
            image_link: ''
            image_loading:
              attribute: lazy
          third_party_settings: {}
    user.role.content_editor:
      grantPermissions:
        - 'delete own files'
        - 'create audio media'
        - 'create document media'
        - 'create image media'
        - 'create media'
        - 'create remote_video media'
        - 'create svg_image media'
        - 'create video media'
        - 'delete any audio media'
        - 'delete any document media'
        - 'delete any image media'
        - 'delete any remote_video media'
        - 'delete any svg_image media'
        - 'delete any video media'
        - 'dropzone upload files'
        - 'edit any audio media'
        - 'edit any document media'
        - 'edit any image media'
        - 'edit any remote_video media'
        - 'edit any svg_image media'
        - 'edit any video media'
        - 'edit own audio media'
        - 'edit own document media'
        - 'edit own image media'
        - 'edit own remote_video media'
        - 'edit own svg_image media'
        - 'edit own video media'
        - 'use media audio bulk upload form'
        - 'use media document bulk upload form'
        - 'use media image bulk upload form'
        - 'use media remote_video bulk upload form'
        - 'use media svg_image bulk upload form'
        - 'use media video bulk upload form'
        - 'use media_bulk_upload bulk upload form'
        - 'view own unpublished media'
    user.role.content_admin:
      grantPermissions:
        - 'delete own files'
        - 'create audio media'
        - 'create document media'
        - 'create image media'
        - 'create media'
        - 'create remote_video media'
        - 'create svg_image media'
        - 'create video media'
        - 'delete any audio media'
        - 'delete any image media'
        - 'delete any remote_video media'
        - 'delete any video media'
        - 'dropzone upload files'
        - 'edit any audio media'
        - 'edit any document media'
        - 'edit any image media'
        - 'edit any remote_video media'
        - 'edit any svg_image media'
        - 'edit any video media'
        - 'edit own audio media'
        - 'edit own document media'
        - 'edit own image media'
        - 'edit own remote_video media'
        - 'edit own svg_image media'
        - 'edit own video media'
        - 'use media audio bulk upload form'
        - 'use media document bulk upload form'
        - 'use media image bulk upload form'
        - 'use media remote_video bulk upload form'
        - 'use media svg_image bulk upload form'
        - 'use media video bulk upload form'
        - 'use media_bulk_upload bulk upload form'
        - 'view own unpublished media'
    user.role.seo_admin:
      grantPermissions:
        - 'delete own files'
        - 'create audio media'
        - 'create image media'
        - 'create media'
        - 'create remote_video media'
        - 'create svg_image media'
        - 'create video media'
        - 'delete any image media'
        - 'delete any remote_video media'
        - 'dropzone upload files'
        - 'edit any image media'
        - 'edit any remote_video media'
        - 'edit own audio media'
        - 'edit own document media'
        - 'edit own image media'
        - 'edit own remote_video media'
        - 'edit own svg_image media'
        - 'edit own video media'
        - 'use media_bulk_upload bulk upload form'
        - 'view own unpublished media'
    user.role.site_admin:
      grantPermissions:
        - 'delete own files'
        - 'create audio media'
        - 'create document media'
        - 'create image media'
        - 'create media'
        - 'create remote_video media'
        - 'create svg_image media'
        - 'create video media'
        - 'delete any audio media'
        - 'delete any image media'
        - 'delete any media'
        - 'delete any remote_video media'
        - 'delete any video media'
        - 'delete media'
        - 'dropzone upload files'
        - 'edit any audio media'
        - 'edit any document media'
        - 'edit any image media'
        - 'edit any remote_video media'
        - 'edit any svg_image media'
        - 'edit any video media'
        - 'edit own audio media'
        - 'edit own document media'
        - 'edit own image media'
        - 'edit own remote_video media'
        - 'edit own svg_image media'
        - 'edit own video media'
        - 'update any media'
        - 'update media'
        - 'use media audio bulk upload form'
        - 'use media document bulk upload form'
        - 'use media image bulk upload form'
        - 'use media remote_video bulk upload form'
        - 'use media svg_image bulk upload form'
        - 'use media video bulk upload form'
        - 'use media_bulk_upload bulk upload form'
        - 'view all media revisions'
        - 'view any audio media revisions'
        - 'view any document media revisions'
        - 'view any image media revisions'
        - 'view any remote_video media revisions'
        - 'view any svg_image media revisions'
        - 'view any video media revisions'
        - 'view own unpublished media'
